apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk011-mariadb
  namespace: skala3-ai1
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "skala123" # 기존에 쓰시던 비번으로 수정하세요
        - name: MARIADB_DATABASE
          value: "skala_stock" # DB 이름 확인!
---
apiVersion: v1
kind: Service
metadata:
  name: sk011-mariadb-svc
  namespace: skala-practice
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 330
